baseURL = 'https://ykeyjp.github.io/ElinMod.Doc/'
languageCode = 'ja-JP'
theme = 'hextra'
title = 'YK Elin Mod Doc'

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = false
hasCJKLanguage = true
defaultContentLanguage = 'ja'
enableInlineShortcodes = true

[frontmatter]
lastmod = [ 'lastmod', ':git' ]

[[module.imports]]
path = 'hextra'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[[menu.main]]
name = 'Docs'
pageRef = '/docs/'
weight = 1
[[menu.main]]
name = 'Search'
weight = 2
params.type = 'search'
[[menu.main]]
name = 'GitHub'
weight = 3
url = "https://github.com/ykeyjp/ElinMod"
params.icon = 'github'
[[menu.main]]
name = 'X'
weight = 4
url = "https://x.com/ykeyjp"
params.icon = 'x-twitter'
[[menu.main]]
name = 'Discord'
weight = 5
url = "https://discord.gg/elona"
params.icon = 'discord'

[params]
description = 'yk elin mod documents.'

[params.navbar]
displayTitle = true
displayLogo = true
width = 'full'
logo.path = 'img/putty.png'

[params.page]
width = 'full'

[params.footer]
displayCopyright = true
displayPoweredBy = false
width = 'full'

[params.editURL]
enable = false
base = ""
